[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sandbox"
version = "0.9.0"
description = "Workflow for setting up, running, calibrating, and evaluating NextGen models."
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Ahmad Jan Khattak", email = "ajkhattak@gmail.com" }]

dependencies = [
    "numpy~=1.0",
    "setuptools>=64.0,<69.0",
    "pandas>=1.1.5,<=2.2.0",
    "xarray",
    "netcdf4<=1.6.3",
    "pyyaml",
    "toolz",
    "joblib",
    "deprecated",
    "pyarrow<12.0",
    "geopandas",
    "fiona",
    "pygeohydro",
    "requests",
    "aiohttp<3.14",
    "Cython>3,!=3.0.4",
    "pycares==4.11.0"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock",
]

[project.urls]
Homepage = "https://github.com/ajkhattak/NextGenSandbox"
Repository = "https://github.com/ajkhattak/NextGenSandbox"
Documentation = "https://ajkhattak.github.io/NextGenSandbox/"
Issues = "https://github.com/ajkhattak/NextGenSandbox/issues"


[project.scripts]
sandbox = "sandbox:main"
sandbox-launcher = "src.python.launcher.cli:main"


[tool.setuptools]
py-modules = ["sandbox"]

[tool.setuptools.packages.find]
include = ["src", "src.python", "src.python.*"]

[tool.setuptools.package-data]
"src.python.launcher" = ["*.sh"]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["test_*.py"]
