# file: calibration_config.yaml
general:
  strategy: 
      # Type of strategy, currently supported is estimation
      type: estimation
      # defaults to dds (currently, the only supported algorithm)
      algorithm: "dds"

  # Enable model runtime logging (captures standard out and error and writes to file)
  # logs will be written to <model.type>.log when enabled
  # defaults to False, which sends all output to /dev/null
  log: True

  start_iteration: 0
  # The total number of search iterations to run
  iterations: 100
  random_seed: 444
  workdir: ./
  
  plugins:
     - "ngen_cal_user_plugins.ngen_cal_save_iteration_output_plugin.SaveValidation"  # saves ngen *.csv to "output_validation" directory
     - "ngen_cal_user_plugins.ngen_cal_read_obs_plugin.ReadObservedData"

# Define parameters to calibrate, their bounds, and initial values.
cfe_params: &cfe_params
  -
    name: b # beta exponent on Clapp-Hornberger (1978) soil water relations
    min: 0.0
    max: 16
    init: 4.05
  - 
    name: satdk # saturated hydraulic conductivity [m/s]
    min: 2.0E-7
    max: 7.26E-3
    init: 3.38E-6
  -
    name: satpsi # saturated capillary head [m]
    min: 0.036
    max: 0.995
    init: 0.355
  -
    name: maxsmc # saturated soil moisture content
    min: 0.2
    max: 0.6
    init: 0.439
  -
    name: max_gw_storage # maximum groundwater storage [m]
    min: 0.01
    max: 0.25
    init: 0.05
  -
    name: Cgw  # groundwater coefficient [m/h]
    min: 1.6266E-6
    max: 1.6266E-4
    init: 1.6266E-5
  -
    name: expon # exponent parameter (1.0 for linear reservoir) (groundwater)
    min: 1.0
    max: 8.0
    init: 5.0
  - 
    name: Kn # Nash cascade lateral subsurface runoff coefficient [1/h]
    min: 0.0
    max: 1.0
    init: 0.03
  - 
    name: Klf # Nash cascade lateral subsurface param - primary reservoir [1/h]
    min: 0.0
    max: 1.0
    init: 0.01
  - 
    name: Kinf_nash_surface # runon infiltration coefficient (NASH CASCADE runoff only; cfe2.0)
    min: 1.0E-6
    max: 5.0E-3
    init: 2.0E-3
  - 
    name: retention_depth_nash_surface # used only with cfe2.0
    min: 0.0
    max: 0.02
    init: 0.001
  -
    name: refkdt # soil infiltration params; used only with Schakee
    min: 0.1
    max: 4.0
    init: 3.0

# Model specific configuration
model:
    type: ngen
    # NOTE: you may need to adjust this to the location of your NextGen installation
    # A binary in $PATH or a qualified path to the binary to run
    binary: "./ngen/cmake_build/ngen"
    realization: ./realization.json
    # Required path to catchment hydrofabirc file
    hydrofabric: ./Gage_1022500.gpkg
    eval_feature: wb-3550
    # Each catchment upstream of observable nexus gets its own permuted parameter space, evaluates at one observable nexus 
    strategy: uniform
    params: 
        CFE: *cfe_params
    
    eval_params:
      # choices are "kling_gupta", "nnse", "custom", "single_peak", "volume"
      objective: "kling_gupta"
    plugins:
      - "ngen_cal_user_plugins.ngen_cal_save_iteration_output_plugin.SaveCalibration" # saves ngen *.csv to "output_iteration" directory
      - "ngen_cal_user_plugins.ngen_cal_save_sim_obs_plugin.SaveCalibration"          # saves simulated and observed discharge at the outlet
      - "ngen_cal_user_plugins.ngen_cal_read_obs_plugin.ReadObservedData"
    plugin_settings:
      ngen_cal_read_obs_data:
        obs_data_path: /home/ec2-user/core/tnc-dangermond/simulations/stream_discharge-19791001-19820929_11120600.csv
        units: "ft3/sec"
        window: 24 # data interval in hours