# See main.py for details about these parameters

#
# See main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir  : "/Users/ahmadjan/codes/workflows/basin_workflow/"
input_dir     : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations"
output_dir    : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations"


gpkg_model_params :
  hf_source                : "/Users/ahmadjan/Core/SimulationsData/preprocessing/hydrofabric_synced"
  dem_input_file           : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/hydrofabric/jldp_dem.tif"
  dem_output_dir           : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations/dem"
  number_processors        : 1
  write_attributes_parquet : FALSE
  reinstall_hydrofabric    : FALSE
  reinstall_arrow          : FALSE

  options :
    use_gage_id :
      use_gage_id : FALSE
      gage_ids    :  "0214655255" #"10154200" #"03366500"
      #gage_ids    : ["04115265", "07301410", "04063700", "12488500"]
      
    use_gage_file :
      use_gage_file : FALSE
      gage_file     : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/CAMELS_v3_calib_BestModelsAll.csv"
      column_name   : "hru_id_CAMELS"

    use_gpkg :
      use_gpkg  : TRUE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr"
      pattern   :  "jldp_ngen_nhdhr_11120600.gpkg"
      

forcings:
  forcing_format     : ".nc"
  forcing_venv_dir   : "/Users/ahmadjan/.ngen_forcing/" # provide only when using forcing data downloaders
  forcing_dir        : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations/11120600/data/forcing/1979_to_1980/"
  forcing_time       : '{"start_time" : "1979-09-20 00:00:00", "end_time" : "2023-09-25 00:00:00"}'

simulations :
  ngen_dir           : "/Users/ahmadjan/codes/ngen/ngen"
  
  simulation_time            : '{"start_time" : "1979-10-01 00:00:00", "end_time" : "1982-09-29 00:00:00"}'
  model_option               : "PET_CFE"

  precip_partitioning_scheme : 'Schaake'
  surface_runoff_scheme      : 'NASH_CASCADE'
  is_routing                 : True

  clean                      : ['existing']
  setup_simulation           : True
  verbosity                  : 0

  num_processors_sim         : 6
  num_processors_adaptive    : False
  num_processors_config      : 1

  rename_existing_simulation : ""
  schema_type                : "dangermond"

ngen_cal :
  task_type        : calibration # calibration, validation, restart, None  
  restart_dir      : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations/11120600/202410011919_ngen_uw17as8j_worker"
  validation_time  : '{"start_time" : "1982-09-30 00:00:00", "end_time" : "2023-09-30 00:00:00"}'
