# file contains list of calibratable parameters for different models

# Define parameters to calibrate, their bounds, and initial values.
# MODEL CFE
cfe_params: &cfe_params
  -
    name: b # beta exponent on Clapp-Hornberger (1978) soil water relations
    min: 0.0
    max: 21.94
    init: 4.05
  - 
    name: satdk # saturated hydraulic conductivity
    min: 0.0
    max: 0.000726
    init: 3.38e-06
  - 
    name: satpsi # saturated capillary head
    min: 0.0
    max: 0.995
    init: 0.355
  - # Maybe parameter
    name: slope # this factor (0-1) modifies the gradient of the hydraulic head at the soil bottom. 0=no-flow.
    min: 0.0
    max: 1.0
    init: 0.01
  - 
    name: maxsmc # saturated soil moisture content
    min: 0.20554
    max: 1.0
    init: 0.439
  - # Maybe parameter
    name: wltsmc # wilting point soil moisture content
    min: 0.0
    max: 0.138
    init: 0.066
  - # Maybe parameter
    name: max_gw_storage # maximum storage in the conceptual reservoir
    min: 0.01
    max: 0.25
    init: 0.016
  - # Maybe parameter
    name: Cgw # the primary outlet coefficient
    # based on the 75% (min), 25% (max), and 50% (init)
    # basin area size from hydrofab v2.1.1
    min: 1.6266115088728495e-06
    max: 3.942439507098691e-06
    init: 2.4530847540782534e-06
  - # Maybe parameter
    name: expon # exponent parameter (1.0 for linear reservoir) (groundwater)
    min: 1.0
    max: 8.0
    init: 6.0
  - # Maybe parameter
    name: alpha_fc # field capacity
    min: 0.1
    max: 1.0
    init: 0.33
  - # Maybe parameter
    name: Kn # Nash Config param for lateral subsurface runoff
    min: 0.0
    max: 1.0
    init: 0.03
  - # Maybe parameter
    name: Klf # Nash Config param - primary reservoir
    min: 0.0
    max: 1.0
    init: 0.01
  - # Maybe parameter, ONLY APPLICABLE TO NASH SURFACE RUNOFF OPTION
    name: Kinf_nash_surface # optional (default = 0.05); storage fraction per hour that moves from reservoirs to soil
    min: 0.0
    max: 1.0
    init: 0.05
  - # Maybe parameter, ONLY APPLICABLE TO NASH SURFACE RUNOFF OPTION
    name: retention_depth_nash_surface # optional (default = 0.001); water retention depth threshold (only applied to the first reservoir)
    min: 0.0
    max: 0.01
    init: 0.001
  -
    name: refkdt # ONLY WITH SCHAKEE
    min: 0.1
    max: 4.0
    init: 3.0
#   - # Maybe parameter
#     name: a_Xinanjiang_inflection_point_parameter # Xinanjiang: Tension water distribution inflection parameter
#     min: 0.001
#     max: 0.017
#     init: 0.001
#   - # Maybe parameter
#     name: b_Xinanjiang_shape_parameter # Xinanjiang: Tension water distribution shape parameter
#     min: 0.0
#     max: 1.0
#     init: 0.5
#   -
#     name: x_Xinanjiang_shape_parameter # Xinanjiang: Tension water distribution shape parameter 
#     min: 0.0
#     max: 6.04
#     init: 3

# MODEL NOM
nom_parameters: &nom_parameters
  -
    name: MFSNO # fractional snow covered area (FSNO) curve parameter (pseduo multiplier)
    min: 0.625
    max: 2.5
    init: 5.0
  -
    name: SCAMAX # maximum fractional snow-covered area
    min: 0.7
    max: 1.0
    init: 1.0
  -
    name: RSURF_SNOW # surface resistence for snow [s/m]
    min: 0.1
    max: 100.0
    init: 50.0
  -
    name: HVT # canopy top height (m)
    min: 0.0
    max: 20.0
    init: 1.0
    name: CWP # canopy wind absorption coefficient (formerly CWPVT) (multiplier)
    # values below derived as absolute values from param tables
    min: 0.18
    max: 5.0
    init: 1.0
  -
    name: VCMX25 # maximum rate of carboxylation at 25c (umol co2/m**2/s) (multiplier)
    # values below derived as absolute values from param tables
    min: 0.0
    max: 80.0
    init: 50.0
  -
    name: MP # slope of conductance-to-photosynthesis relationship (multiplier)
    # values below derived as absolute values from param tables
    min: 3.6
    max: 12.6
    init: 9.0

# MODEL LASAM