# See main.py for details about these parameters

#
# See main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir  : "/Users/ahmadjan/codes/workflows/basin_workflow/basin_workflow/"
output_dir    : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations"


gpkg_model_params :
  hf_source                : "/Users/ahmadjan/Core/SimulationsData/preprocessing/hydrofabric_synced"
  dem_input_file           : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/hydrofabric/jldp_dem.tif"
  dem_output_dir           : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations/dem"
  number_processors        : 1
  write_attributes_parquet : FALSE
  reinstall_hydrofabric    : FALSE
  reinstall_arrow          : FALSE

  options :
    use_gage_id :
      use_gage_id : FALSE
      gage_ids    :  "0214655255" #"10154200" #"03366500"
      #gage_ids    : ["04115265", "07301410", "04063700", "12488500"]
      
    use_gage_file :
      use_gage_file : FALSE
      gage_file     : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/CAMELS_v3_calib_BestModelsAll.csv"
      column_name   : "hru_id_CAMELS"

    use_gpkg :
      use_gpkg  : TRUE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr"
      pattern   :  "jldp_ngen_nhdhr_11120600.gpkg"
      
###############
simulations :
  ngen_dir           : "/Users/ahmadjan/codes/ngen/ngen"
  is_netcdf_forcing  : True
  forcing_source     : "Nels_forcing_prep" # if forcing data are downloaded using Nels tools 'forcing_prep'
  forcing_venv_dir   : "/Users/ahmadjan/.ngen_forcing/" # "/home/ec2-user/venv_forcing" # provide only when using forcing data downloaders
  
  #simulation_time        : '{"start_time" : "1979-10-01 00:00:00", "end_time" : "1982-09-29 00:00:00"}'
  #simulation_time        : '{"start_time" : "1979-10-01 00:00:00", "end_time" : "1979-10-05 00:00:00"}'
  simulation_time        : '{"start_time" : "1979-10-05 00:00:00", "end_time" : "1979-10-15 00:00:00"}'
  model_option               : "PL"
  precip_partitioning_scheme : 'Schaake'
  surface_runoff_scheme      : 'NASH_CASCADE'
  is_routing                 : True

  clean                      : ['existing']
  setup_simulation           : True
  verbosity                  : 0

  num_processors_sim         : 1
  num_processors_adaptive    : False
  num_processors_config      : 1

  rename_existing_simulation : ""
  schema_type                : "dangermond"

ngen_cal :
  #task_type  : calibration #, validation, restart
  #task_type  : validation # #calibration, validation, restart
  task_type : None
  state_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/tnc-dangermond/ngen-dr/simulations/11120600/202410011919_ngen_uw17as8j_worker"
  #cal_evaluation_time        : '{"start_time" : "1979-10-05 00:00:00", "end_time" : "1979-10-15 00:00:00"}'
  #val_evaluation_time        : '{"start_time" : "1979-10-05 00:00:00", "end_time" : "1979-10-15 00:00:00"}'