# file: calibration_config.yaml
general:
  strategy: 
      # Type of strategy, currently supported is estimation
      type: estimation
      # defaults to dds (currently, the only supported algorithm)
      algorithm: "dds"

  # Enable model runtime logging (captures standard out and error and writes to file)
  # logs will be written to <model.type>.log when enabled
  # defaults to False, which sends all output to /dev/null
  log: True

  start_iteration: 0
  # The total number of search iterations to run
  iterations: 100
  random_seed: 444
  workdir: ./

# Define parameters to calibrate, their bounds, and initial values.
cfe_params: &cfe_params
  -
    name: b # beta exponent on Clapp-Hornberger (1978) soil water relations
    min: 0.0
    max: 21.94
    init: 4.05
  -
    name: satdk # saturated hydraulic conductivity
    min: 0.0
    max: 0.000726
    init: 3.38e-06
  -
    name: satpsi # saturated capillary head
    min: 0.0
    max: 0.995
    init: 0.355

  -
    name: maxsmc # saturated soil moisture content
    min: 0.20554
    max: 0.6
    init: 0.439

  -
    name: max_gw_storage # maximum storage in the conceptual reservoir
    min: 0.01
    max: 0.2
    init: 0.05

  -
    name: Cgw  #groundwater coefficient
    min: 1.6266e-06
    max: 0.1
    init: 1.6266e-05

  -
    name: expon # exponent parameter (1.0 for linear reservoir) (groundwater)
    min: 1.0
    max: 8.0
    init: 5.0

  - 
    name: Kn # Nash Config param for lateral subsurface runoff
    min: 0.0
    max: 1.0
    init: 0.03

  - 
    name: Klf # Nash Config param - primary reservoir
    min: 0.0
    max: 1.0
    init: 0.01
 
  - 
    name: Kinf_nash_surface # runon infiltration coefficient (NASH CASCADE runoff only; cfe2.0)
    min: 0.001
    max: 0.005
    init: 0.002

  - 
    name: retention_depth_nash_surface # used only with CFE2.0
    min: 0.0
    max: 0.02
    init: 0.001
  -
    name: refkdt # used only with Schakee
    min: 0.1
    max: 4.0
    init: 3.0

# Model specific configuration
model:
    type: ngen
    # NOTE: you may need to adjust this to the location of your NextGen installation
    # A binary in $PATH or a qualified path to the binary to run
    binary: "./ngen/cmake_build/ngen"
    realization: ./realization.json
    # Required path to catchment hydrofabirc file
    hydrofabric: ./Gage_1022500.gpkg
    eval_feature: wb-3550
    # Each catchment upstream of observable nexus gets its own permuted parameter space, evaluates at one observable nexus 
    strategy: independent
    params: 
        CFE: *cfe_params
    
    eval_params:
      # choices are "kling_gupta", "nnse", "custom", "single_peak", "volume"
      objective: "kling_gupta"
    plugins:
      - "ngen_cal_user_plugins.ngen_cal_save_iteration_output_plugin.NgenSaveOutput" # saves cat_*.csv or nex-*.csv to "output_iteration" directory
      - "ngen_cal_user_plugins.ngen_cal_save_sim_obs_plugin.SaveOutput"              # saves simulated and observed discharge at the outlet