# See main.py for details about these parameters

#
# See main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir  : "/home/ec2-user/codes/workflows/basin_workflow/basin_workflow"
output_dir     : "/home/ec2-user/simulations/cfe_camas_evaluation/test"

gpkg_model_params :
  hf_source                : "/Users/ahmadjan/Core/SimulationsData/preprocessing/hydrofabric_synced"
  dem_output_dir           : "/Users/ahmadjan/Core/SimulationsData/projects/ngen-bm/dem"
  number_processors        : 1
  write_attributes_parquet : FALSE
  reinstall_hydrofabric    : FALSE
  reinstall_arrow          : FALSE

  options :
    use_gage_id :
      use_gage_id : TRUE
      gage_ids    :  "03366500"
      #gage_ids    : ["04115265", "07301410", "04063700", "12488500"]
      
    use_gage_file :
      use_gage_file : FALSE
      gage_file     : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/CAMELS_v3_calib_BestModelsAll.csv"
      column_name   : "hru_id_CAMELS"

    use_gpkg :
      use_gpkg  : FALSE
      #gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/test/test_gpkg"
      pattern   :  "Gage_"
      
###############
simulations :
  ngen_dir           : "/home/ec2-user/codes/ngen/ngen"
  is_netcdf_forcing  : True
  #forcing_source     : "local" #"Nels_forcing_prep"
  forcing_source     : "Nels_forcing_prep" # if forcing data are downloaded using Nels tools 'forcing_prep'
  forcing_dir        : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/forcingsX/{*}"
  forcing_venv_dir   : "/home/ec2-user/venv_forcing" # provide only when using forcing data downloaders
  
  simulation_time            : '{"start_time" : "2010-10-01 00:00:00", "end_time" : "2010-10-02 00:00:00"}'
  model_option               : "NCP"
  precip_partitioning_scheme : 'Schaake'
  surface_runoff_scheme      : 'NASH_CASCADE' # 'GIUH' for cfe1.0
  is_routing                 : True    
  is_calibration             : True

  clean                      : ['existing']
  setup_simulation           : True
  verbosity                  : 3

  num_processors_sim         : 1
  num_processors_adaptive    : False
  num_processors_config      : 1

  rename_existing_simulation : ""
