#
# See main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir          : "/Users/ahmadjan/codes/workflows/basin_workflow/basin_workflow/"
output_dir            : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/test"
hf_source             : "/Users/ahmadjan/Core/SimulationsData/preprocessing/hydrofabricS3"
#
number_processors     : 2
reinstall_hydrofabric : FALSE
reinstall_arrow       : FALSE

#
options :
   use_gage_id :
      use_gage_id : TRUE
      gage_ids    : "01052500"
      #gage_ids    : ["04115265", "07301410", "04063700", "12488500"]
      

   use_gage_file :
      use_gage_file : FALSE
      gage_file   : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/CAMELS_v3_calib_BestModelsAll.csv"
      column_name : "hru_id_CAMELS"

   use_gpkg :
      use_gpkg  : FALSE
      #gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/basins_gpkgs_all"
      gpkg_dir : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/test/test_gpkg"
      pattern   :  "Gage_"
