# See main.py for details about these parameters

#
# See main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir  : "/Users/ahmadjan/codes/workflows/NextGenSandboxHub"
input_dir   : "/Users/ahmadjan/Core/projects/testing/input"
output_dir    : "/Users/ahmadjan/Core/projects/testing/output"


# to subset a location using hydrofabric
subsetting :
  hf_version               : "2.2" # Only enter version number, e.g. "2.2" or "2.1.1"
  # Ensure that this gpkg matches the hf_version specified above:
  hf_gpkg_path             : "/Users/ahmadjan/Core/projects/hf2.2_gpkgs/conus_nextgen.gpkg" 
  dem_output_dir           : "/Users/ahmadjan/Core/projects/testing/input/dem" # create `dem` directory yourself
  number_processors        : 1


  options :
    use_gage_id :
      use_gage_id : TRUE
      # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
      gage_ids     : ["11147500"] # ["08010000"]
    use_gage_file :
      use_gage_file : FALSE
      # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
      gage_file     : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/rfc_ids_clean_conus.csv"
      column_name   : "USGS.ID"

    use_gpkg :
      use_gpkg  : FALSE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen-bm/test/gpkgs"
      pattern   :  "hf_v211_"


forcings: 
  forcing_format     : ".nc" 
  forcing_venv_dir   : "/Users/ahmadjan/.ngen_forcing/" # provide only when using forcing data downloaders
  forcing_dir        : "/Users/ahmadjan/Core/projects/testing/input/{*}/data/forcing/2010_to_2011/" # start year and end year +1 ; Before the asterisk should be the same as your input_dir above
  forcing_time       : '{"start_time" : "2010-10-01 00:00:00", "end_time" : "2010-09-30 23:00:00"}' 

formulation :
  ngen_dir           : "/Users/ahmadjan/codes/ngen/ngen"
  
  models                     : "PET, CFE-S, T-route"
  surface_runoff_scheme      : 'NASH_CASCADE' # 'GIUH' for cfe1.0

  clean                      : ['existing']
  setup_simulation           : True
  verbosity                  : 0

  np_per_basin               : 1         # number of processors for basin partitioning
  np_per_basin_adaptive      : False     # adaptive - set by the workflow
  basins_in_par              : 1         # use for both config files and simulations

simulation :
  task_type : "calibvalid"
  #task_type        : "calibvalid"  #calibration #, validation, restart, None
  calibration_time : '{"start_time" : "2010-10-01 00:00:00", "end_time" : "2010-10-30 23:00:00"}'
  calib_eval_time  : '{"start_time" : "2010-10-05 00:00:00", "end_time" : "2010-10-30 23:00:00"}'
  validation_time  : '{"start_time" : "2010-11-22 14:00:00", "end_time" : "2010-12-23 02:00:00"}'
  valid_eval_time  : '{"start_time" : "2010-11-23 14:00:00", "end_time" : "2010-12-23 02:00:00"}'
  restart_dir      : "/Users/ahmadjan/Core/SimulationsData/projects/test_basins/{*}/202410042024_ngen_qaiklwj0_worker/"
