# See main.py for details about these parameters

#
# See main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir  : "/Users/laurenbolotin/Lauren/basin_workflow"
input_dir   : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/input"
output_dir    : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/output"



gpkg_model_params :
  hf_version               : "2.2" # Only enter version number, e.g. "2.2" or "2.1.1"
  # Ensure that this gpkg matches the hf_version specified above:
  hf_gpkg_path             : "/Users/laurenbolotin/Lauren/hydrofabric/data/v2.2/conus_nextgen.gpkg" 
  dem_output_dir           : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/dem"
  # Path to NLCD data for vegetation type calculation
  nlcd_data_path           : "/home/seth/noaa/GIS_data/nlcd/Annual_NLCD_LndCov_2021_CU_C1V1/Annual_NLCD_LndCov_2021_CU_C1V1.tif"
  calculate_vegetation     : FALSE  # Set to FALSE to skip vegetation calculation
  number_processors        : 4
  write_attributes_parquet : FALSE
  reinstall_hydrofabric    : FALSE
  reinstall_arrow          : FALSE

  options :
    use_gage_id :
      use_gage_id : FALSE
      # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
      gage_ids     : ["11147500"]
    use_gage_file :
      use_gage_file : TRUE
      # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
      gage_file     : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/rfc_ids_clean_conus.csv"
      column_name   : "USGS.ID"

    use_gpkg :
      use_gpkg  : FALSE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen-bm/test/gpkgs"
      pattern   :  "hf_v211_"


forcings: 
  forcing_format     : ".nc" 
  forcing_venv_dir   : "/Users/laurenbolotin/.venv_forcing/" # provide only when using forcing data downloaders
  forcing_dir        : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/{*}/data/forcing/2016_to_2024/" # start year and end year +1 ; Before the asterisk should be the same as your output directory abov
  forcing_time       : '{"start_time" : "2016-10-01 00:00:00", "end_time" : "2023-09-30 23:00:00"}' 

formulation :
  ngen_dir           : "/Users/ahmadjan/codes/ngen/ngen"
  
  models                     : "PET_CFE"
  precip_partitioning_scheme : 'Schaake'
  surface_runoff_scheme      : 'NASH_CASCADE' # 'GIUH' for cfe1.0
  is_routing                 : True

  clean                      : ['existing']
  setup_simulation           : True
  verbosity                  : 0

  np_per_basin               : 1         # number of processors for basin partitioning
  np_per_basin_adaptive      : False     # adaptive - set by the workflow
  basins_in_par              : 2         # use for both config files and simulations

  rename_existing_simulation : ""

ngen_cal :
  task_type        : "calibvalid"  #calibration #, validation, restart, None
  calibration_time : '{"start_time" : "2010-10-01 00:00:00", "end_time" : "2010-10-30 23:00:00"}'
  calib_eval_time  : '{"start_time" : "2010-10-05 00:00:00", "end_time" : "2010-10-23 02:00:00"}'
  validation_time  : '{"start_time" : "2010-11-22 14:00:00", "end_time" : "2010-12-23 02:00:00"}'
  valid_eval_time  : '{"start_time" : "2010-11-23 14:00:00", "end_time" : "2010-12-23 02:00:00"}'
  restart_dir      : "/Users/ahmadjan/Core/SimulationsData/projects/test_basins/{*}/202410042024_ngen_qaiklwj0_worker/"