# See main.py for details about these parameters

#
# See main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir  : "/Users/ahmadjan/codes/workflows/basin_workflow/"
input_dir     : "/Users/ahmadjan/Core/SimulationsData/projects/tests_ss/"
output_dir    : "/Users/ahmadjan/Core/SimulationsData/projects/tests_ss/"


gpkg_model_params :
  hf_source                : "/Users/ahmadjan/Core/SimulationsData/preprocessing/hydrofabric_synced"
  dem_output_dir           : "/Users/ahmadjan/Core/SimulationsData/projects/test_basinsX/dem"
  number_processors        : 1
  write_attributes_parquet : FALSE
  reinstall_hydrofabric    : FALSE
  reinstall_arrow          : FALSE

  options :
    use_gage_id :
      use_gage_id : TRUE
      #gage_ids    :  "0214655255" #"10154200" #"03366500"
      #gage_ids    : ["04115265", "07301410", "04063700", "12488500"]
      gage_ids     : ["02378300", "02471078", "02381600", "02465000"]
    use_gage_file :
      use_gage_file : FALSE
      gage_file     : "/Users/ahmadjan/Core/SimulationsData/projects/ngen_evaluation_camels/CAMELS_v3_calib_BestModelsAll.csv"
      column_name   : "hru_id_CAMELS"

    use_gpkg :
      use_gpkg  : FALSE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen-bm/test/gpkgs"
      pattern   :  "hf_v211_"


forcings:
  forcing_format     : ".nc"
  forcing_venv_dir   : "/Users/ahmadjan/.ngen_forcing/" # provide only when using forcing data downloaders
  forcing_dir        : "/Users/ahmadjan/Core/SimulationsData/projects/tests_ss/{*}/data/forcing/2010_to_2011/"
  forcing_time       : '{"start_time" : "2010-09-20 00:00:00", "end_time" : "2010-09-25 00:00:00"}'
  

simulations :
  ngen_dir           : "/Users/ahmadjan/codes/ngen/ngen"
  
  #simulation_time            : '{"start_time" : "2010-10-01 00:00:00", "end_time" : "2010-10-05 00:00:00"}'
  simulation_time            : '{"start_time" : "2010-10-05 00:00:00", "end_time" : "2010-10-05 23:00:00"}'
  model_option               : "PET_CFE"
  precip_partitioning_scheme : 'Schaake'
  surface_runoff_scheme      : 'NASH_CASCADE' # 'GIUH' for cfe1.0
  is_routing                 : True

  clean                      : ['existing']
  setup_simulation           : True
  verbosity                  : 0

  num_processors_sim         : 1
  num_processors_adaptive    : False
  num_processors_config      : 1

  rename_existing_simulation : ""

ngen_cal :
  task_type       : validation #calibration #, validation, restart, None
  restart_dir     : "/Users/ahmadjan/Core/SimulationsData/projects/test_basins/{*}/202410042024_ngen_qaiklwj0_worker/"
  validation_time : '{"start_time" : "2010-11-22 14:00:00", "end_time" : "2010-12-23 02:00:00"}'
