# Sandbox configuration sample file
#

general:
  input_dir  : "<path_to_input_directory>"  #-------------------------- user-specified input directory (directory where all geopackage files are written when downloaded through the workflow, or where user-supplied gpkg files must be placed.)
  output_dir : "<path_to_output_directory>" #-------------------------- user-specified output directory (directory where simulation outputs are written)


########################################################################
# Subset a basin using hydrofabric; see src/R/main.R for further details
# make sure to install yaml package using install.packages("yaml") if not installed already
subsetting :
  hydrofabric:
    version               : "2.2" #-------------------------------------- Only enter version number, e.g. "2.2" or "2.1.1"
    # Ensure that this gpkg matches the hf_version specified above:
    gpkg_path             : "<path_to>/conus_nextgen.gpkg"  #------------ For example, "<paht_to>/conus_nextgen.gpkg", download it from https://proxy.lynker-spatial.com/hydrofabric/v2.2/conus
  dem:
    output_dir           : "dem"    #-------------------------------- If set to null string, the dem.tif and associated files will be deleted at the end. If provide an absolute path, all .tif files will be moved to that directory.
    input_file           : "<path_to>/dem.vrt" #--------------------- Set to local dem.vrt file (download it from https://proxy.lynker-spatial.com/gridded/3DEP/USGS_seamless_DEM_13.vrt), or leave it empty # (OPTIONAL)
    aggregate_factor : 3 # ------------------------------------------ Aggregation factor to coarsen the DEM resolution; default is 3 for 10 cm DEM to get 30 x 30 m grids

  vegetation:
  # Path to NLCD data for vegetation type (IVGTYP) calculation
    enabled                  : FALSE  #---------------------------------------- Set to FALSE to skip vegetation calculation # OPTIONAL
    nlcd_path                : "<path_to>/Annual_NLCD_LndCov_2021_CU_C1V1.tif" # OPTIONAL (see src/R/main.R for more details)
    classification_method    : "fraction"  #----------------------------------- vegetation classfication method (majority or fraction). Defaults to 'majority' method

  # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
  gages:
    option: "ids"   # ------------------------------------------ OPTIONS: ids | file | gpkg

    ids: ["01308000"] #----------------------------------------- List of gage IDs, for instance, ["01105000","08070500"]

    file:
      path: "<path_to_basin_ids_file>/basin_ids_file.csv" #----- Path to CSV file with column (set column name below) of basin gage IDs
      column: "USGS.ID" #--------------------------------------- Name of column of gage IDs

    gpkg:
      dir: "<path_to_gpkgs_dir>" #------------------------------- Path to base directory for all (already downloaded/processed) geopackages (or path to .gpkg file).
      pattern: "gage_" #----------------------------------------- Pattern of names, e.g., gage_<*> or hf_<*>
      select: ["HUC_VPUID03W"] #--------------------------------- Selected gages/gpkgs from the directory gpkg_dir


########################################################################
#forcing data is stored under <input_dir>/gage_id/data/forcing
forcings : 
  format  : ".nc" #----------------------------------------------- Format .nc or .csv (recommended option .nc)
  time    : {"start_time" : "2016-10-01 00:00:00", "end_time" : "2020-09-30 23:00:00"} #---------- Forcing data time range [1-1-2016,12-31-2020]; simulation start/end times must fall within this period

  domain  : "conus"    #-------------------------------------------- options = ["conus", "HI", "PR", 'AK']
  select  : "01308000" #-------------------------------------------- Provide a single gage id, or list of ids, or a .csv file (with columns gage_id and num_divides) or "all" to download data for all gages in the input_dir
########################################################################
formulation :
  #ngen_dir         : "<path_to_ngen_dir>" #------------------------------- OPTIONAL: Path to NextGen base directory. For instance, <path_to_ngen>/ngen. Defaults is <path_to_sandbox>/extern/ngen
  models            : "PET, CFE, T-route"  #------------------------------- Formulation. Run "sandbox -h" to see a complete list of supported formulations

  clean             : ['existing'] #--------------------------------------- Clean existing config and realization files (does not delete simulation data)
  verbosity         : 0            #--------------------------------------- Verbosity levels (Set to 0 recommended unless debugging)

  num_procs         : 4            #--------------------------------------- Number of processors for basin partitioning

simulation :
  task_type        : "<pick_option>" #------------------------------------- Supported options: calibvalid, calibration, validation, restart, control
  gage_ids_input   :  "01308000"   #--------------------------------------- Provide a single gage id, or list of ids, or a .csv file (with columns gage_id and num_divides)
  sim_name_suffix  :  "pet_cfe" #------------------------------------------ User specified name appended to the gage_id. For example, 01105000_pet_cfe
  #simulation_time : {"start_time" : "2016-10-01 00:00:00", "end_time" : "2018-09-30 23:00:00"} # only needed when task_type is control
  calibration_time : {"start_time" : "2016-10-01 00:00:00", "end_time" : "2018-09-30 23:00:00"} # Entire simulation period for calibration; including spinup period
  calib_eval_time  : {"start_time" : "2017-10-01 00:00:00", "end_time" : "2018-09-30 23:00:00"} # Evalaution period for calibration (excluding spinup period)
  validation_time  : {"start_time" : "2018-10-01 00:00:00", "end_time" : "2020-09-30 23:00:00"} # Entire simulation period for validation; including spinup period
  valid_eval_time  : {"start_time" : "2019-10-01 00:00:00", "end_time" : "2020-09-30 23:00:00"} # Evalaution period for validation (excluding spinup period)
  restart_dir      : "<path_to_restart_dir>/{*}/202410042024_ngen_qaiklwj0_worker/" #----------- Restart experiment from the best iteration
  
  ensemble:
    enabled: FALSE # ---------------------------------------------------------------- Ensemble ON/OFF (OPTIONS: TRUE/FALSE)
    calib_params_groups: #------------------------------------------- scope of calibratable parameters: local = tile-specific, global = shared across tiles
      NOM : local
      CFE-S : global