# make sure to install yaml package using install.packages("yaml") if not installed already

workflow_dir  : "<path_to>/NextGenSandboxHub"
input_dir     : "<path_to_input_dir>" ! user-specified
output_dir    : "<path_to_output_dir>" ! user-specified


########################################################################
# Subset a basin using hydrofabric; see src/R/main.R for further details
subsetting :
  hf_version               : "2.2" # Only enter version number, e.g. "2.2" or "2.1.1"
  # Ensure that this gpkg matches the hf_version specified above:
  hf_gpkg_path             : "<path_to_HF_gpkg_file>"  #for example, "<paht_to>/conus_nextgen.gpkg"
  dem_output_dir           : "<path_to_input_dir>/dem" # create `dem` directory yourself
  number_processors        : 1

  # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
  options :
    use_gage_id :
      use_gage_id  : TRUE
      gage_ids     : <provide_gage_id_or_list_of_ids> #for instance, ["01105000"]
    use_gage_file :
      use_gage_file : FALSE
      gage_file     : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/rfc_ids_clean_conus.csv"
      column_name   : "USGS.ID"
    use_gpkg :
      use_gpkg  : FALSE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen-bm/test/gpkgs"
      pattern   :  "hf_v211_"

########################################################################
forcings : 
  forcing_format     : ".nc" 
  forcing_venv_dir   : "<path_to_venv_forcing>" # the python environment created in Step 4 (see Readme)
  forcing_dir        : "<path_to_input_dir>/{*}/data/forcing/2016_to_2024/" # start year and end year +1; Before the asterisk should be the same as your input_dir above
  forcing_time       : '{"start_time" : "2016-10-01 00:00:00", "end_time" : "2023-09-30 23:00:00"}' 

########################################################################
formulation :
  ngen_dir           : "<path_to_ngen_dir>" # for instance, /Users/ajkhattak/codes/ngen_repo/ngen"
  models             : "NOM, CFE, T-route"

  clean              : ['existing']
  setup_simulation   : True
  verbosity          : 0

  np_per_basin           : 1         # number of processors for basin partitioning
  np_per_basin_adaptive  : False     # adaptive - set by the workflow
  basins_in_par          : 1         # use for both config files and simulations

simulation :
  task_type : "<pick_option>" # calibvalid, calibration, validation, restart, None
  calibration_time : '{"start_time" : "2016-10-01 00:00:00", "end_time" : "2021-09-30 23:00:00"}'
  calib_eval_time  : '{"start_time" : "2017-10-01 00:00:00", "end_time" : "2021-09-30 23:00:00"}'
  validation_time  : '{"start_time" : "2010-11-22 14:00:00", "end_time" : "2010-12-23 02:00:00"}'
  valid_eval_time  : '{"start_time" : "2010-11-23 14:00:00", "end_time" : "2010-12-23 02:00:00"}'
  restart_dir      : "<path_to_restart_dir>/{*}/202410042024_ngen_qaiklwj0_worker/" # TODO
  
