verbosity           : none

soil_params_file    : null

layer_thickness     : 200.0          # [cm]
initial_psi         : 2000.0         # [cm]

timestep            : 3600           # [sec]
endtime             : 1000000000.0   # [d]
forcing_resolution  : 3600           # [sec]

ponded_depth_max    : 0.0            # [cm]

use_closed_form_G   : true

layer_soil_type       : null
max_valid_soil_types  : 25

wilting_point_psi     : 15495.0        # [cm]
field_capacity_psi    : 340.9          # [cm]

adaptive_timestep     : true

giuh_ordinates        : null

a                     : 0.0001
b                     : 3.0

frac_to_GW            : 0.4

PET_affects_precip    : false

spf_factor            : 0.6

free_drainage_enabled : true
free_drainage_to_CR   : true
allow_flux_caching    : true

calib_params          : null
log_mode              : true

sft_coupled           : false
soil_z : "10.0,15.0,18.0,23.0,29.0,36.0,44.0,55.0,69.0,86.0,107.0,134.0,166.0,207.0,258.0,322.0,401.0,500.0,600.0"
sft_calib   : false