# make sure to install yaml package using install.packages("yaml") if not installed already

sandbox_dir  : "/Users/ahmadjankhattak/Code/workflows/NextGenSandboxHub"
input_dir     : "/Users/ahmadjankhattak/Core/projects/testing/input2_fix" # user-specified
#input_dir     : "/Users/ahmadjankhattak/Core/projects/nwm_bm_sims/input2" # user-specified


# PET RUNS
#output_dir    : "/Users/ahmadjankhattak/Core/projects/nwm_bm_sims/nom_cfe_set5"
#output_dir    : "/Users/ahmadjankhattak/Core/projects/nwm_bm_sims/nom_topmodel_set1"
output_dir    : "/Users/ahmadjankhattak/Core/projects/nwm_bm_sims/nom_pet_cfe_set4"

#output_dir    : "/Users/ahmadjankhattak/Core/projects/nwm_bm_sims/pet_cfe_set1"

########################################################################
# Subset a basin using hydrofabric; see src/R/main.R for further details
subsetting :
  hf_version               : "2.2" # Only enter version number, e.g. "2.2" or "2.1.1"
  # Ensure that this gpkg matches the hf_version specified above:
  hf_gpkg_path             : "/Users/ahmadjankhattak/Core/input_data/hf2.2_gpkgs/conus_nextgen.gpkg"
  dem_output_dir           : "/Users/ahmadjankhattak/Core/projects/testing/dem" # create `dem` directory yourself
  number_processors        : 1

  # Note: only gage_ids that fall within the domain of the hydrofabric listed above will be subsetted
  options :
    use_gage_id :
      use_gage_id  : TRUE
      gage_ids     : ["10011500", "09112500", "10310000","09217900"]
    use_gage_file :
      use_gage_file : FALSE
      gage_file     : "/Users/laurenbolotin/Lauren/benchmark/benchmark2.0_final/rfc_ids_clean_conus.csv"
      column_name   : "USGS.ID"
    use_gpkg :
      use_gpkg  : FALSE
      gpkg_dir  : "/Users/ahmadjan/Core/SimulationsData/projects/ngen-bm/test/gpkgs"
      pattern   :  "hf_v211_"

########################################################################
forcings : 
  forcing_format     : ".nc"
  #forcing_time       : {"start_time" : "1994-10-01 00:00:00", "end_time" : "2012-09-30 23:00:00"}
  forcing_time       : {"start_time" : "2015-10-01 00:00:00", "end_time" : "2022-09-30 23:00:00"}

########################################################################
formulation :
  ngen_dir           : "/Users/ahmadjankhattak/Code/ngen/ngen"
  models             : <*> #"NOM, CFE, T-route"

  clean              : ['existing']
  verbosity          : 0

  np_per_basin           : 2         # number of processors for basin partitioning
  np_per_basin_adaptive  : False     # adaptive - set by the workflow
  basins_in_par          : 1         # use for both config files and simulations

simulation :
  task_type   : "calibration" # calibvalid, calibration, validation, restart, control
  gage_ids    :  <*>
  sim_name_suffix : "nwm_calib_setAB6" # user specified name; used a suffix
  #simulation_time : {"start_time" : "2015-10-01 00:00:00", "end_time" : "2020-09-30 23:00:00"}
  calibration_time : {"start_time" : "2015-10-01 00:00:00", "end_time" : "2017-09-30 23:00:00"}
  calib_eval_time  : {"start_time" : "2016-10-01 00:00:00", "end_time" : "2017-09-30 23:00:00"}
  validation_time  : {"start_time" : "2015-10-01 00:00:00", "end_time" : "2020-09-30 23:00:00"}
  valid_eval_time  : {"start_time" : "2016-10-01 00:00:00", "end_time" : "2020-09-30 23:00:00"}
  restart_dir : "/Users/ahmadjankhattak/Core/projects/nwm_bm_sims/nom_pet_cfe_set4/10011500_nwm_calib_setAB6/202509271300_ngen_3ru8b5ba_worker"
  
sandbox_launcher :
  exp_info : True
  exp_info_dir : "exp_info_dir1"
