# file: calibration_config.yaml
general:
  strategy: 
      # Type of strategy, currently supported is estimation
      type: estimation
      # defaults to dds (currently, the only supported algorithm)
      algorithm: "dds"

  # Enable model runtime logging (captures standard out and error and writes to file)
  # logs will be written to <model.type>.log when enabled
  # defaults to False, which sends all output to /dev/null
  log: True

  start_iteration: 0
  # The total number of search iterations to run
  iterations: 500
  random_seed: 444
  workdir: ./

# Define parameters to calibrate, their bounds, and initial values for CFE with Schaake
cfes_params: &cfes_params
  -
    name: b # beta exponent on Clapp-Hornberger (1978) soil water relations
    min: 0.0
    max: 15
    init: 4.05
  -
    name: satdk # saturated hydraulic conductivity
    min: 0.0
    max: 0.00726
    init: 3.38e-04
  -
    name: satpsi # saturated capillary head
    min: 0.0
    max: 0.995
    init: 0.355
  -
    name: maxsmc # saturated soil moisture content
    min: 0.16
    max: 0.6
    init: 0.439
  -
    name: max_gw_storage # maximum storage in the conceptual reservoir
    min: 0.01
    max: 0.25
    init: 0.05
  -
    name: Cgw  #groundwater coefficient
    min: 1.8e-06
    max: 1.8E-3
    init: 1.8e-04
  -
    name: expon # exponent parameter (1.0 for linear reservoir) (groundwater)
    min: 1.0
    max: 8.0
    init: 5.0
  - 
    name: Kn # Nash Config param for lateral subsurface runoff
    min: 0.0
    max: 1.0
    init: 0.3
  - 
    name: Klf # Nash Config param - primary reservoir
    min: 0.0
    max: 1.0
    init: 0.1
  #- 
  #  name: Kinf_nash_surface # runon infiltration coefficient (NASH CASCADE runoff only; cfe2.0)
  #  min: 0.0001
  #  max: 1.0
  #  init: 0.0005 

  #- 
  #  name: retention_depth_nash_surface # used only with CFE2.0
  #  min: 0.0
  #  max: 0.1
  #  init: 0.00001
  -
    name: refkdt # used only with Schakee
    min: 0.001
    max: 8.0
    init: 3.0

  # these params can be calibrated as well
  -   
    name: slope # this factor (0-1) modifies the gradient of the hydraulic head at the soil bottom. 0=no-flow.
    min: 0.0
    max: 1.0
    init: 0.01

  - # Maybe parameter
    name: wltsmc # wilting point soil moisture content
    min: 0.0
    max: 0.138
    init: 0.066
  - 
    name: alpha_fc # field capacity
    min: 0.15
    max: 0.33
    init: 0.20

# Define parameters to calibrate, their bounds, and initial values for CFE with Xinanjiang
cfex_params: &cfex_params
  -
    name: b # beta exponent on Clapp-Hornberger (1978) soil water relations
    min: 0.0
    max: 15
    init: 4.05
  -
    name: satdk # saturated hydraulic conductivity
    min: 0.0
    max: 0.00726
    init: 3.38e-04
  -
    name: satpsi # saturated capillary head
    min: 0.0
    max: 0.995
    init: 0.355
  -
    name: maxsmc # saturated soil moisture content
    min: 0.16
    max: 0.6
    init: 0.439
  -
    name: max_gw_storage # maximum storage in the conceptual reservoir
    min: 0.01
    max: 0.25
    init: 0.05
  -
    name: Cgw  #groundwater coefficient
    min: 1.8e-06
    max: 1.8E-3
    init: 1.8e-04
  -
    name: expon # exponent parameter (1.0 for linear reservoir) (groundwater)
    min: 1.0
    max: 8.0
    init: 5.0
  - 
    name: Kn # Nash Config param for lateral subsurface runoff
    min: 0.0
    max: 1.0
    init: 0.3
  - 
    name: Klf # Nash Config param - primary reservoir
    min: 0.0
    max: 1.0
    init: 0.1
  #- 
  #  name: Kinf_nash_surface # runon infiltration coefficient (NASH CASCADE runoff only; cfe2.0)
  #  min: 0.0001
  #  max: 1.0
  #  init: 0.0005 

  #- 
  #  name: retention_depth_nash_surface # used only with CFE2.0
  #  min: 0.0
  #  max: 0.1
  #  init: 0.00001
  -
    name: refkdt # used only with Schakee
    min: 0.001
    max: 8.0
    init: 3.0

  # these params can be calibrated as well
  -   
    name: slope # this factor (0-1) modifies the gradient of the hydraulic head at the soil bottom. 0=no-flow.
    min: 0.0
    max: 1.0
    init: 0.01

  - # Maybe parameter
    name: wltsmc # wilting point soil moisture content
    min: 0.0
    max: 0.138
    init: 0.066
  - 
    name: alpha_fc # field capacity
    min: 0.15
    max: 0.33
    init: 0.20

  # Calibratable parameters for CFE Xinanjiang water partitioning scheme
  -
    name: a_Xinanjiang_inflection_point_parameter # Xinanjiang: Tension water distribution inflection parameter
    min: -0.493
    max: 0.493
    init: 0.25
  -
    name: b_Xinanjiang_shape_parameter # Xinanjiang: Tension water distribution shape parameter
    min: 9.0e-4
    max: 10.0
    init: 2.5
  -
    name: x_Xinanjiang_shape_parameter # Xinanjiang: Tension water distribution shape parameter
    min: 5.0e-4
    max: 10.0
    init: 2.5

####################################################################################
topmodel_params: &topmodel_params
  -
    name: szm
    init: 0.032
    min: 0.001
    max: 0.2
  -
    name: sr0
    init: 0.002
    min: 0.001
    max: 0.04
  -
    name: srmax
    init: 0.05
    min: 0.001
    max: 1
  -
    name: td
    init: 50
    min: 0.001
    max: 100
  -
    name: t0
    init: 5
    min: -8
    max: 8
  -
    name: chv
    init: 3600
    min: 100
    max: 4000
  -
    name: rv
    init: 1000
    min: 10
    max: 4000

####################################################################################
noahowp_params: &noahowp_params
  -
    name: MFSNO # fractional snow covered area (FSNO) curve parameter (pseduo multiplier)
    min: 0.5
    max: 4.0
    init: 2.5
  -
    name: SCAMAX # maximum fractional snow-covered area
    min: 0.7
    max: 1.0
    init: 0.8
  -
    name: RSURF_SNOW # surface resistence for snow [s/m]
    min: 0.136
    max: 100.0
    init: 50.0
  -
    name: CWP # canopy wind absorption coefficient (formerly CWPVT) (multiplier)
    # values below derived as absolute values from param tables
    min: 0.09
    max: 0.36
    init: 0.1
  -
    name: VCMX25 # maximum rate of carboxylation at 25c (umol co2/m**2/s) (multiplier)
    # values below derived as absolute values from param tables
    min: 20.0 
    max: 120.0 
    init: 40.0
  -
    name: MP # slope of conductance-to-photosynthesis relationship (multiplier)
    # values below derived as absolute values from param tables
    min: 3.6
    max: 12.6
    init: 9.0
  -
    name: RSURF_EXP # surface resistence for snow [s/m]
    min: 1.0
    max: 6.0
    init: 3.0
  -
    name: SHDMAX # annual maximum fraction of surface covered by vegetation
    min: 0.05
    max: 0.95
    init: 0.5  

####################################################################################
snow17_params: &snow17_params
  -
    "name": "scf"
    "min": 0.7
    "max": 1.7
    "init": 1.15
  -
    "name": "mfmax"
    "min": 0.5
    "max": 2.2
    "init": 1.35
  -
    "name": "mfmin"
    "min": 0.1
    "max": 0.6
    "init": 0.35
  -
    "name": "uadj"
    "min": 0.05
    "max": 0.2
    "init": 0.125
  -
    "name": "si"
    "min": 1
    "max": 9999
    "init": 999
  -
    "name": "adc2"
    "min": 0.110
    "max": 0.300
    "init": 0.243
  -
    "name": "adc3"
    "min": 0.200
    "max": 0.520
    "init": 0.423
  -
    "name": "adc4"
    "min": 0.450
    "max": 0.650
    "init": 0.578
  -
    "name": "adc5"
    "min": 0.500
    "max": 0.770
    "init": 0.688
  -
    "name": "adc6"
    "min": 0.560
    "max": 0.810
    "init": 0.734
  -
    "name": "adc7"
    "min": 0.610
    "max": 0.860
    "init": 0.785
  -
    "name": "adc8"
    "min": 0.650
    "max": 0.890
    "init": 0.819
  -
    "name": "adc9"
    "min": 0.690
    "max": 0.930
    "init": 0.859
  -
    "name": "adc10"
    "min": 0.820
    "max": 0.960
    "init": 0.919


# Model specific configuration
model:
    type: ngen
    binary: <*>
    realization: <*>

    hydrofabric: <*>
    eval_feature: <*>
    # Each catchment upstream of observable nexus gets its own permuted parameter space, evaluates at one observable nexus 
    strategy: uniform
    params:
        <*>
    eval_params:
      # choices are "kling_gupta", "nnse", "custom", "single_peak", "volume"
      objective: "kling_gupta"
      target : "min"
      #objective: "nnse"
      #target : "max"
    plugins:
      - "ngen_cal_user_plugins.save_divide_output_plugin.SaveData" # saves cat_*.csv or nex-*.csv to "output_iteration" directory
      - "ngen_cal_user_plugins.save_sim_obs_plugin.SaveData"          # saves simulated and observed discharge at the outlet
      - "ngen_cal_user_plugins.metrics.ComputeMetrics"
      - "ngen_cal_user_plugins.read_obs_plugin.ReadObservedData"
    plugin_settings:
      read_obs_data:
        obs_data_path: /Users/ahmadjankhattak/Core/projects/nwm_bm_sims/usgs_obs_streamflow
